module.exports = {
    SWITCH_3_BTN_LEFT: ['Ee\\d<CC-0'],
    SWITCH_3_BTN_MIDDLE: ['Ee\\d<CE-0'],
    SWITCH_3_BTN_RIGHT: ['Ee\\d<Ce-0'],

    CERCLE_1_UP: ['IZUFJVFZZIVZZYZZZVEUI-1', 'IZUFJVFZZIVZZYZZJJZZV-1'],
    CERCLE_1_MILDDLE: ['IZUFJVFZZIVZZYZZJZUZJ-1'],
    CERCLE_1_DOWN: ['IZUFJVFZZIVZZYZZVZUVJ-1', 'IZUFJVFZZIVZZYZZJJZZV-1'],

    CERCLE_2_UP: ['IZUFJVFZZIVZJZZZZVEUU-1', 'IZUFJVFZZIVZJZZZJJZZV-1'],
    CERCLE_2_MILDDLE: ['IZUFJVFZZIVZJZZZJZUZV-1'],
    CERCLE_2_DOWN: ['IZUFJVFZZIVZJZZZVZUVV-1', 'IZUFJVFZZIVZJZZZJJZZV-1'],

    CERCLE_3_UP: ['IZUFJVFZZIVZVZZZZVEUE-1', 'IZUFJVFZZIVZVZZZJJZZF-1'],
    CERCLE_3_MILDDLE: ['IZUFJVFZZIVZVZZZJZUZF-1'],
    CERCLE_3_DOWN: ['IZUFJVFZZIVZVZZZVZUVF-1', 'IZUFJVFZZIVZVZZZJJZZF-1'],

    CERCLE_4_UP: ['IZUFJVFZZIVZYZZZZVEEJ-1', 'IZUFJVFZZIVZYZZZJJZZI-1'],
    CERCLE_4_MILDDLE: ['IZUFJVFZZIVZYZZZJZUZI-1'],
    CERCLE_4_DOWN: ['IZUFJVFZZIVZYZZZVZUVI-1', 'IZUFJVFZZIVZYZZZJJZZI-1'],

    CERCLE_5_UP: ['IZUFJVFZZIVJZZZZZVEEI-1', 'IZUFJVFZZIVJZZZZJJZJJ-1'],
    CERCLE_5_MILDDLE: ['IZUFJVFZZIVJZZZZJZUJJ-1'],
    CERCLE_5_DOWN: ['IZUFJVFZZIVJZZZZVZUFJ-1', 'IZUFJVFZZIVJZZZZJJZJJ-1'],

    CERCLE_6_UP: ['IZUFJVFZZIVVZZZZZVUZI-1', 'IZUFJVFZZIVVZZZZJJZVJ-1'],
    CERCLE_6_MILDDLE: ['IZUFJVFZZIVVZZZZJZUVJ-1'],
    CERCLE_6_DOWN: ['IZUFJVFZZIVVZZZZVZUYJ-1', 'IZUFJVFZZIVVZZZZJJZVJ-1'],

    CERCLE_ALL_UP: ['IZUFJVFZZIVFEYZZZVUVY-1', 'IZUFJVFZZIVFEYZZJJZYJ-1'],
    CERCLE_ALL_MILDDLE: ['IZUFJVFZZIVFEYZZJZUYZ-1'],
    CERCLE_ALL_DOWN: ['IZUFJVFZZIVFEYZZVZUUZ-1', 'IZUFJVFZZIVFEYZZJJZYJ-1'],
};